sudo: required
services:
  - docker

before_install:
  - docker build -t tommy/docker-react -f Dockerfile.dev .

script:
  - docker run tommy/docker-react npm run test -- --coverage

deploy:
  provide: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-234249885524"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"



  



